site_name: Sopa
repo_name: gustaveroussy/sopa
repo_url: https://github.com/gustaveroussy/sopa
copyright: Copyright &copy; 2023 - 2024 Quentin Blampey
theme:
  name: material
  logo: assets/sopa_small_white.png
  favicon: assets/sopa_favicon.png
  features:
    - content.code.annotate
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tutorials:
    - Snakemake pipeline: tutorials/snakemake.md
    - CLI usage: tutorials/cli_usage.md
    - API usage: tutorials/api_usage.ipynb
    - Explorer usage: tutorials/xenium_explorer/explorer.ipynb
    - Align images (e.g. H&E): tutorials/align.md
    - Spatial statistics: tutorials/spatial.ipynb
    - H&E usage: tutorials/he.ipynb
    - Advanced segmentation: tutorials/advanced_segmentation.md
  - CLI: cli.md
  - API:
    - sopa.spatial: api/spatial.md
    - sopa.segmentation:
      - sopa.segmentation.shapes: api/segmentation/shapes.md
      - sopa.segmentation.aggregate: api/segmentation/aggregate.md
      - sopa.segmentation.stainings: api/segmentation/stainings.md
      - sopa.segmentation.methods: api/segmentation/methods.md
      - sopa.segmentation.patching: api/segmentation/patching.md
      - sopa.segmentation.tissue: api/segmentation/tissue.md
      - sopa.segmentation.baysor: api/segmentation/baysor.md
    - sopa.io: api/io.md
    - sopa.annotation: api/annotation.md
    - sopa.utils:
      - sopa.utils.image: api/utils.py/image.md
      - sopa.utils.polygon_crop: api/utils.py/polygon_crop.md
    - sopa.patches: api/patches.md
    - sopa._sdata: api/_sdata.md
  - Frequently asked questions: faq.md
  - Cite us: cite_us.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            heading_level: 3
  - mkdocs-jupyter:
      include_source: True
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/termynal.css
  - css/custom.css
extra_javascript:
  - js/termynal.js
  - js/custom.js
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
